version: '3.1'

services:
  db:
    image: 'mongo'
    environment:
      MONGO_INITDB_DATABASE: contas
    ports:
      - 27017:27017
    volumes:
      - contas_data:/var/lib/mongo

volumes:
  contas_data: